### ISSUE TITLE
公众号图片挂了？、

### ISSUE THREAD

**Issue by janglichao** [aalansehaiyang/technology-talk#12]

**Comment by aalansehaiyang** [comment]
github图片加载有点慢，重新换了个CDN链接，现在可以秒开

**Comment by join-wjp** [comment]
您好，您发的邮件已收到，非常感谢！-----温金萍

**Comment by musuifeng** [comment]
您好,您的邮件我已收到,会尽快回复.
                                    马浩杰

**Comment by LudanLink** [comment]
您好，邮件已收到。我将尽快给您回复，谢谢。
