### ISSUE TITLE
分布式锁

### ISSUE THREAD

**Issue by gang-yu** [aalansehaiyang/technology-talk#14]
写的挺好。我觉得可以再完善一下
1. lock-db
可以增加一个缺点说明： 单点故障后，其获得的锁无法释放。
所以lock-zk那已经提到了，但是这里再说说，比较完整
2. lock-redis
zk、db的做法在 archeteture那已经说了，lock-redis没有。
补上最好了。

**Comment by answercome** [comment]
good
