### ISSUE TITLE
Check out this post… "technology!!".

### ISSUE THREAD

**Issue by Paralelinertia** [aalansehaiyang/technology-talk#16]
http://devikababunadumparambil.blogspot.com/2022/10/technology.html

**Comment by Paralelinertia** [comment]
Hi it is so interesting

**Comment by musuifeng** [comment]
您好,您的邮件我已收到,会尽快回复.
                                    马浩杰

**Comment by join-wjp** [comment]
您好，您发的邮件已收到，非常感谢！-----温金萍
